### ISSUE TITLE
Mise a jour Xdecor et Moreblocks

### ISSUE THREAD

**Issue by Jat15** [turbogus/steinheim-nodesnation#3]
## Xdecor:

- Crée des unknow block si on mes pas tous les mods utilisé par lui en depends.
- Permet multiplier les block coupé.
  Prendre un des blocks coupé et faire un clic droit pour déposé qu'un seul dans l'inventaire du joueur.
- Des conflit avec moreblocks dans la scie circulaire et craft.

- [x] Rajouté une options pour désactivé le workbench https://github.com/minetest-mods/xdecor/pull/83
- [x] Une compatibilité avec moreblock pour les craft https://github.com/minetest-mods/moreblocks/pull/82

## Moreblocks:

Se réinitialise si on essayer de faire de la multiplication d'objet

- [x] Crée des alias pour convertir les block de Xdecor https://github.com/minetest-mods/moreblocks/pull/88

## Modifier:

- [x] Ajouté des compatibilité avec moreblocks https://github.com/turbogus/steinheim-nodesnation/issues/4
- [x] Ambience
- [x] Clear pour nettoyer tout ce qui sera inutile et amélioré
- [x] Moreblocks
  - [x]   **Crée un dépôt qui modifie le listring et la , conversion xdecor (sans incidence pour un retour sur la version originale ).** https://github.com/Jat15/moreblocks/tree/Steinheim-Fix
  - [x] moreblocks_craft - Mod pour modifier les craft qui rentre en collision avec Xdecor.
- [x] Xdecor
  - [x] **Créations d'un dépôt pour pouvoir retiré le workbench. (Incidence la version futur, mais est ce qu'on va le gardé ? )**  https://github.com/Jat15/xdecor/tree/Big-patch-1
- [x] Bobblocks 

## Supprimé:

- [x] Lifter , Meshnode , Mycorner, Pep

## Ajouté:

- [x] Abriglass
- [x] Abripanes
- [x] Titend glass doors
- [x] Advtrains #6 
- [x] Stairsplus_add
- [x] moreblocks_craft

# A revoir
- [x] Pinewood alias 
- [x] Tar conversion ajouter a Building_blocks
- [x] Passé minetes game 0.4.16
  - Nyancat a supprimé

**Comment by turbogus** [comment]
Peut etre également proposer la modification au developpeur de xdecor pour qu'il l'intègre dans son mod (cela évitera de modifier le code à chaque mise à jour du mod dans le dépot steinheim-nodesnation)
